    <div class="breadcrumb-area bg-img bg-overlay" style="background-image: url(assets/img/27.jpg);">
        <div class="container h-100">
            <div class="row h-100 align-items-center">
                <!-- Breadcrumb Text -->
                <div class="col-12">
                    <div class="breadcrumb-text">
                        <h2>Terminos y Condiciones</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <section class="game-review-area section-padding-100" style="margin-top: -80px;">
        <dir class="container">
            <p>Bienvenido al sitio de internet NN Games , (en adelante el "Sitio"). Los términos y condiciones, que se describen a continuación (en adelante los "Términos y Condiciones") tienen por objeto regular el uso que realicen las personas que ingresen al Sitio. Por "Usuario" del website se entiende tanto a los registrados como a los visitantes, (en adelante el "Usuario").Al registrarse y/o navegar en el Sitio, el Usuario presta su consentimiento al presente.</p>

            <p>Los Términos y Condiciones así como las Políticas de Privacidad y/o informaciones sobre el Sitio se considerarán de aplicación para todo Usuario del Sitio desde el primer momento en que accedan al mismo. Los presentes términos y condiciones tienen carácter obligatorio y vinculante. Se aplican a todas las compras y actividades realizadas en el Sitio. Si el Usuario no acepta en forma total los presentes Términos y Condiciones, y las Políticas de Privacidad, le rogamos que no avance en el acceso y visita de nuestro Sitio. En caso de avanzar en la visita a nuestro Sitio, se entenderá que el Usuario aceptó los presentes Términos y Condiciones, la Política de Privacidad y acepta recibir mails periódicos con la información que el Sitio determine. Los Términos y Condiciones y la Política de Privacidad podrán ser modificados en todo o en parte en cualquier momento y a exclusivo criterio de BFOOT,dichos cambios e implementaciones tendrán vigencia a partir del momento mismo en que sean publicados o insertados en el Sitio o desde que sean notificados al Usuario por cualquier medio, lo que ocurra primero. Por lo expuesto, le sugerimos que los visite periódicamente. Las violaciones a los Términos y Condiciones generarán el derecho en favor del titular del Sitio a suspender o terminar la prestación del servicio al Usuario que las haya realizado, por acción u omisión. El Sitio se preocupa por la protección de datos de carácter personal de los Usuarios, de acuerdo a los lineamientos expuestos en nuestra Política de Privacidad.</p> 

            <p>Los productos y servicios que se ofrecen por medio del Sitio (en adelante los "Productos"), sólo están disponibles para personas que tengan capacidad legal para contratar. Por lo tanto, aquellos que no cumplan con esta condición deberán abstenerse de suministrar información personal para ser incluida en nuestras bases de datos. Sin embargo pueden hacerlo a través de sus padres o tutores. Los padres, tutores o responsables de los menores de edad o incapaces que utilicen el Sitio serán responsables por dicho uso, incluyendo cualquier cargo, facturación o daño que se derive de él. Si el Usuario está registrado como Empresa, deberá tener capacidad para contratar a nombre de tal entidad y de obligar a la misma en los términos del presente. </p>

            <h4>Responsabilidad</h4>
            <p>El Usuario es responsable de toda afirmación y/o expresión y/o acto celebrado con su nombre de usuario y contraseña. El Sitio se reserva el derecho, en cualquier momento y sin necesidad de darle notificación previa, de retirar cualquier envío o dar por concluido su calidad de miembro del Sitio por violación de los Términos y Condiciones aquí descriptos. En caso de que la información o los datos suministrados por el usuario no sean verdaderos, este será responsable por los daños que este hecho pudiera ocasionar.</p>

            <p>El Usuario acepta y reconoce que el sistema puede no siempre estar disponible debido a dificultades técnicas o fallas de Internet, o por cualquier otro motivo ajeno al Sitio, motivo por el cual no podrá imputársele responsabilidad alguna. El contenido del Sitio, junto con y sin que se considere una limitación, sus logotipos, programas, bases de datos, imágenes, textos información y archivos son de propiedad de NN Games.</p>

            <p>Su uso indebido así como su reproducción sin el expreso y escrito consentimiento previo de NN Games serán objeto de las acciones judiciales que correspondan. El presente acuerdo no podrá ser interpretado como un contrato de sociedad, mandato o que genere ningún tipo de relación entre el Sitio y el Usuario. El uso de Internet y el Sitio implica la asunción de riesgos de daños al software y al hardware del usuario. Documentos y archivos pueden contener virus y, como es el caso de cualquier computadora interconectada, la computadora del Usuario puede ser atacada por hackers que podrían tener acceso a la información contenida en la computadora del Usuario, extraerla o dañarla. El envío de información a través de la red o a través de e-mails tiene el riesgo de que tal información pueda ser captada por un tercero. El Sitio no se hace responsable de las consecuencias que pudiera acarrear al Usuario la asunción por parte del Usuario de ese riesgo. El Sitio no tiene obligación alguna de conservar ninguna información que haya hecho disponible a los Usuarios ni que le haya sido enviada por los Usuarios. Las funciones contenidas en el Sitio y el acceso al mismo pueden ser interrumpidas en cualquier momento y contener errores.</p> 

            <p>Para adquirir los Productos ofrecidos por el Sitio, los Usuarios deberán facilitar determinados datos de carácter personal. Su información personal será procesada y almacenada en servidores de NN Games. Para mayor información sobre la privacidad de los Datos Personales y casos en los que será revelada la información personal, se pueden consultar nuestras Políticas de Privacidad.</p>

            <p>Disponibilidad / Precio de productos: La información sobre productos y precios está sujeta a cambios sin previo aviso. Todos los precios expresados en el Sitio incluyen IVA, salvo que se indique lo contrario. Todos los precios en el Sitio están expresados en pesos argentinos, moneda de curso legal de la República Argentina. No se permite la modalidad de cambio de producto por el mismo modelo y mismo talle, salvo que el cambio se deba a un defecto del producto. Antes de comprar, el Usuario deberá tener en cuenta que los productos seleccionados pueden no encontrarse disponibles. Toda compra se encuentra sujeta a disponibilidad. El Sitio solamente opera vía internet. Por este motivo, puede ocurrir que, por más que sea posible ordenar la compra de un Producto en el Sitio, no haya existencias de éste, por razones imputables a las firmas que proveen los productos al Sitio. Del mismo modo, el precio de los Productos que ofrecemos en el Sitio, puede no coincidir con el de los distintos locales o proveedores que nos abastecen. Validez de las promociones: En el caso de que se realicen ofertas y promociones de Productos, éstas tendrán validez para las compras efectuadas desde la fecha de comienzo de las mismas, hasta la de finalización de la oferta según lo expuesto en el Sitio. Los términos y condiciones de las mismas serán comunicados en el Sitio, y estarán siempre sujetas a la existencia en stock de los Productos ofrecidos.</p>
        </div>
    </section>